export const guidedWorkflows = [
  {
    id: "core-employee-lifecycle-v1",
    title: "Core Employee Lifecycle",
    description: "Baseline walkthrough for the employee journey from recruiting through retirement.",
    version: "1.0",
    product: "Oracle Fusion Cloud HCM",
    nodes: [
      {
        id: "recruit",
        title: "Recruit & Onboard",
        subtitle: "Attract and prepare the right talent.",
        objective: "Build candidate pipeline, align role expectations, and prep the first-day experience.",
        visuals: ["Role profile brief", "Candidate funnel snapshot", "Welcome checklist"],
        walkthrough: [
          "Open with the role objective and business priority.",
          "Overlay key screenshots that show job req intake and approvals.",
          "Add contextual notes that explain what to validate before onboarding starts.",
        ],
        checkpoint: {
          prompt: "What makes this node complete?",
          options: ["The onboarding checklist is approved", "The final payroll run is posted", "Offboarding surveys are sent"],
          answer: 0,
        },
        checkpointPlacement: "end",
        reward: 30,
      },
      {
        id: "hire",
        title: "Hire & Position",
        subtitle: "Convert offers into active worker records.",
        objective: "Capture legal employer, position, and assignment details with strong data quality.",
        visuals: ["Offer letter capture", "Position assignment card", "Data validation panel"],
        walkthrough: [
          "Highlight each screen and annotate which fields are non-negotiable.",
          "Show a callout layer for common setup mistakes.",
          "Pause for a mini-quiz so users can identify the correct hiring sequence.",
        ],
        checkpoint: {
          prompt: "Which detail is critical during hire processing?",
          options: ["Legal employer and assignment", "Expense report category", "Supplier payment terms"],
          answer: 0,
        },
        checkpointPlacement: "middle",
        reward: 35,
      },
      {
        id: "develop",
        title: "Manage & Develop",
        subtitle: "Guide performance, growth, and retention.",
        objective: "Drive manager coaching, goal tracking, and role-readiness progression.",
        visuals: ["Goal dashboard", "Learning plan timeline", "Performance note feed"],
        walkthrough: [
          "Use a phased storyboard to explain manager actions at each milestone.",
          "Attach visuals for coaching notes and learning progress.",
          "Insert a challenge question after each phase to keep momentum game-like.",
        ],
        checkpoint: {
          prompt: "Why include challenge questions between visuals?",
          options: ["To reinforce understanding before advancing", "To hide unavailable actions", "To skip review checkpoints"],
          answer: 0,
        },
        checkpointPlacement: "middle",
        reward: 40,
      },
      {
        id: "reward",
        title: "Pay & Reward",
        subtitle: "Connect work outcomes to compensation.",
        objective: "Explain payroll, bonus, and rewards workflows with transparency and controls.",
        visuals: ["Payroll readiness board", "Compensation statement", "Audit confirmation strip"],
        walkthrough: [
          "Map each visual to a policy checkpoint.",
          "Contextualize calculations with plain-language annotations.",
          "Prompt a checkpoint question that confirms the user can identify release criteria.",
        ],
        checkpoint: {
          prompt: "Before payroll release, teams should verify:",
          options: ["Approved inputs and validation checks", "Social post scheduling", "Supplier onboarding status"],
          answer: 0,
        },
        checkpointPlacement: "end",
        reward: 45,
      },
      {
        id: "retire",
        title: "Exit & Retire",
        subtitle: "Close the journey and capture insight.",
        objective: "Handle offboarding, knowledge transfer, and retirement events with consistency.",
        visuals: ["Exit checklist", "Knowledge handoff note", "Final archive confirmation"],
        walkthrough: [
          "Walk through final approvals in sequence with visual stamps.",
          "Annotate transfer and archive expectations.",
          "Use a final challenge question to validate full process understanding.",
        ],
        checkpoint: {
          prompt: "The final node should always include:",
          options: ["A complete offboarding confirmation", "Open candidate requisitions", "Pending learning enrollments"],
          answer: 0,
        },
        checkpointPlacement: "end",
        reward: 50,
      },
    ],
  },
  {
    id: "otl-time-to-pay-v1",
    title: "Oracle Time & Labor — Timecard to Paycheck",
    description: "Capture → Validate → Approve → Transfer → Calculate → Pay with checkpoint-driven debugging.",
    version: "1.0",
    product: "Oracle Fusion Cloud HCM",
    modules: ["Time and Labor", "Payroll"],
    nodes: [
      {
        id: "node1-capture",
        title: "Capture — Enter Time",
        subtitle: "Employee enters the right hours in the right period.",
        objective: "Saved time is captured data, not payroll-ready pay.",
        visuals: ["Time and Absences landing", "Current Time Card period", "Saved draft totals"],
        walkthrough: [
          "Open Time and Absences and confirm the correct period before entering hours.",
          "Add a line with required values (for example project or payroll time type) and save.",
          "Verify the card is in saved/draft status and totals reflect the entry.",
        ],
        checkpoint: {
          prompt: "Saved time means it will be paid automatically in payroll.",
          options: ["True", "False"],
          answer: 1,
        },
        checkpointPlacement: "end",
        reward: 50,
      },
      {
        id: "node2-validate",
        title: "Validate — Submit and Resolve Exceptions",
        subtitle: "Submission enforces configured time-entry rules.",
        objective: "Errors block submission; warnings may allow it depending on configuration.",
        visuals: ["Submit Time Card action", "Validation message panel", "Submitted status"],
        walkthrough: [
          "Submit the time card and classify returned messages as warnings versus errors.",
          "Fix blocking errors such as missing required fields, then submit again.",
          "Confirm status changes to Submitted or Submitted for Approval.",
        ],
        checkpoint: {
          prompt: "Which message type typically blocks timecard submission?",
          options: ["Warning", "Error"],
          answer: 1,
        },
        checkpointPlacement: "end",
        reward: 50,
      },
      {
        id: "node3-approve",
        title: "Approve — Manager Reviews Team Time Cards",
        subtitle: "Manager approval is a gate before payroll transfer.",
        objective: "Approved time is not yet in payroll until transfer runs.",
        visuals: ["Team Time Cards list", "Submitted employee card", "Approved status"],
        walkthrough: [
          "Navigate to Team Time Cards and open a submitted employee card.",
          "Review totals and exceptions, then approve or reject with comments.",
          "Confirm approved cards are ready for payroll transfer processing.",
        ],
        checkpoint: {
          prompt: "A timecard that's approved is automatically in payroll.",
          options: ["True", "False"],
          answer: 1,
        },
        checkpointPlacement: "end",
        reward: 50,
      },
      {
        id: "node4-transfer",
        title: "Transfer — Send Approved Time to Payroll",
        subtitle: "Payroll admins run the handoff process.",
        objective: "Transfer is the true bridge between approved time and payroll consumption.",
        visuals: ["Scheduled Processes", "Transfer Time Cards flow", "Transfer output and exceptions"],
        walkthrough: [
          "Open Scheduled Processes (or payroll flow submission in your setup).",
          "Run Transfer Time Cards from Time and Labor with the right filters and dates.",
          "Monitor completion and inspect output for transferred counts and exceptions.",
        ],
        checkpoint: {
          prompt: "Which step is the true bridge that moves time data into payroll processing?",
          options: ["Approve", "Transfer", "Capture"],
          answer: 1,
        },
        checkpointPlacement: "end",
        reward: 50,
      },
      {
        id: "node5-calculate",
        title: "Calculate — Run Payroll Calculation",
        subtitle: "QuickPay validates that transferred time is payable.",
        objective: "Missing or zero pay is often a transfer issue before a calculation issue.",
        visuals: ["Calculate QuickPay", "Person and payroll parameters", "Statement of Earnings"],
        walkthrough: [
          "Open Calculate QuickPay, pick the worker, and verify payroll parameters.",
          "Submit QuickPay and review results for critical calculation issues.",
          "If results are wrong, trace back in order: Calculate → Transfer → Approve → Validate → Capture.",
        ],
        checkpoint: {
          prompt: "If pay is $0 or missing earnings, the best first place to check is:",
          options: [
            "Whether time transferred to payroll successfully",
            "Whether the manager approved it",
            "Whether the employee saved the timecard",
          ],
          answer: 0,
        },
        checkpointPlacement: "end",
        reward: 50,
      },
      {
        id: "node6-pay",
        title: "Pay — Confirm Payment and Learn the Trace",
        subtitle: "Validate payment outputs and trace issues from symptom to source.",
        objective: "Most reliable diagnosis starts at pay outcome and traces backward upstream.",
        visuals: ["Payment process outputs", "Employee trace check", "Debugging direction"],
        walkthrough: [
          "Confirm payments were generated in payroll outputs without critical issues.",
          "Trace one employee from timecard line to transfer, payroll result, and payment record.",
          "Memorize troubleshooting direction: Pay → Calculate → Transfer → Approve → Validate → Capture.",
        ],
        checkpoint: {
          prompt: "When diagnosing a pay issue, the most reliable direction is:",
          options: ["Start at Capture and move forward", "Start at Pay and trace backward"],
          answer: 1,
        },
        checkpointPlacement: "end",
        reward: 50,
      },
    ],
  },
];
